
server:
  port: 8080

spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true